[package]
name = "nzoth"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
insta = {version = "1.43.1", features = ["glob"]}

[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3
